# Миграции вниз не откатываем — чиним новой (backend/CLAUDE.md).
"""initial schema

Revision ID: 00daf3248f9b
Revises: 
Create Date: 2026-08-16 02:39:44.409835

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '00daf3248f9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_code',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_code'))
    )
    op.create_index(op.f('ix_auth_code_phone'), 'auth_code', ['phone'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('short', sa.Text(), server_default='', nullable=False),
    sa.Column('full', sa.Text(), server_default='', nullable=False),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('duration_text', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('starts_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lang IN ('ru', 'kz')", name=op.f('ck_course_lang')),
    sa.CheckConstraint("status IN ('draft', 'planned', 'open', 'closed', 'hidden')", name=op.f('ck_course_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course')),
    sa.UniqueConstraint('group_id', 'lang', name=op.f('uq_course_group_id_lang'))
    )
    op.create_index(op.f('ix_course_group_id'), 'course', ['group_id'], unique=False)
    op.create_table('setting',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_setting'))
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), server_default='', nullable=False),
    sa.Column('last_name', sa.Text(), server_default='', nullable=False),
    sa.Column('middle_name', sa.Text(), server_default='', nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), server_default='', nullable=False),
    sa.Column('school', sa.Text(), server_default='', nullable=False),
    sa.Column('position', sa.Text(), server_default='', nullable=False),
    sa.Column('region', sa.Text(), server_default='', nullable=False),
    sa.Column('city', sa.Text(), server_default='', nullable=False),
    sa.Column('subject', sa.Text(), server_default='', nullable=False),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('lang', sa.Text(), server_default='ru', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lang IN ('ru', 'kz')", name=op.f('ck_user_lang')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('phone', name=op.f('uq_user_phone'))
    )
    op.create_table('certificate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('holder_name', sa.Text(), nullable=False),
    sa.Column('course_title', sa.Text(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_certificate_course_id_course')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_certificate_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificate')),
    sa.UniqueConstraint('number', name=op.f('uq_certificate_number'))
    )
    op.create_index(op.f('ix_certificate_course_id'), 'certificate', ['course_id'], unique=False)
    op.create_index(op.f('ix_certificate_user_id'), 'certificate', ['user_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_note', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_enrollment_course_id_course')),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], name=op.f('fk_enrollment_granted_by_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_enrollment_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment')),
    sa.UniqueConstraint('user_id', 'course_id', name=op.f('uq_enrollment_user_id_course_id'))
    )
    op.create_index(op.f('ix_enrollment_course_id'), 'enrollment', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollment_user_id'), 'enrollment', ['user_id'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('price_snapshot', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default='new', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_lead_course_id_course')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lead_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead'))
    )
    op.create_index(op.f('ix_lead_course_id'), 'lead', ['course_id'], unique=False)
    op.create_index(op.f('ix_lead_user_id'), 'lead', ['user_id'], unique=False)
    op.create_table('module',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_module_course_id_course')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module'))
    )
    op.create_index(op.f('ix_module_course_id'), 'module', ['course_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_review_rating')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_review_course_id_course')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_review_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.create_index(op.f('ix_review_course_id'), 'review', ['course_id'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.Text(), server_default='', nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_session_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_session_token_hash'))
    )
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('video_provider', sa.Text(), server_default='youtube', nullable=False),
    sa.Column('duration_label', sa.Text(), nullable=True),
    sa.Column('time_required_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("(kind = 'video' AND video_url IS NOT NULL) OR (kind = 'text' AND body IS NOT NULL)", name=op.f('ck_lesson_kind_content')),
    sa.CheckConstraint("kind IN ('video', 'text')", name=op.f('ck_lesson_kind')),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('fk_lesson_module_id_module')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson'))
    )
    op.create_index(op.f('ix_lesson_module_id'), 'lesson', ['module_id'], unique=False)
    op.create_table('quiz',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('time_limit_min', sa.Integer(), nullable=True),
    sa.Column('shuffle', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('show_review', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('retakable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('time_required_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('fk_quiz_module_id_module')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz'))
    )
    op.create_index(op.f('ix_quiz_module_id'), 'quiz', ['module_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('statement', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_file', sa.Text(), nullable=True),
    sa.Column('submit_format', sa.Text(), server_default='both', nullable=False),
    sa.Column('allowed_ext', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('max_size_mb', sa.Integer(), server_default='20', nullable=False),
    sa.Column('time_required_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("submit_format IN ('text', 'file', 'both')", name=op.f('ck_task_submit_format')),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('fk_task_module_id_module')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.create_index(op.f('ix_task_module_id'), 'task', ['module_id'], unique=False)
    op.create_table('lesson_file',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_lesson_file_lesson_id_lesson'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_file'))
    )
    op.create_index(op.f('ix_lesson_file_lesson_id'), 'lesson_file', ['lesson_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_lesson_progress_lesson_id_lesson')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lesson_progress_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'lesson_id', name=op.f('pk_lesson_progress'))
    )
    op.create_table('question',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), server_default='1', nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("type IN ('single', 'multi', 'bool')", name=op.f('ck_question_type')),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name=op.f('fk_question_quiz_id_quiz')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    op.create_index(op.f('ix_question_quiz_id'), 'question', ['quiz_id'], unique=False)
    op.create_table('quiz_attempt',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('question_order', postgresql.ARRAY(sa.BigInteger()), server_default='{}', nullable=False),
    sa.Column('is_counted', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name=op.f('fk_quiz_attempt_quiz_id_quiz')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_quiz_attempt_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempt'))
    )
    op.create_index(op.f('ix_quiz_attempt_quiz_id'), 'quiz_attempt', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_user_id'), 'quiz_attempt', ['user_id'], unique=False)
    op.create_index('uq_quiz_attempt_counted', 'quiz_attempt', ['user_id', 'quiz_id'], unique=True, postgresql_where=sa.text('is_counted'))
    op.create_table('submission',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_submission_reviewed_by_user')),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_submission_task_id_task')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_submission_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission'))
    )
    op.create_index(op.f('ix_submission_task_id'), 'submission', ['task_id'], unique=False)
    op.create_index(op.f('ix_submission_user_id'), 'submission', ['user_id'], unique=False)
    op.create_table('thread_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('lesson_id', sa.BigInteger(), nullable=True),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_thread_message_course_id_course')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_thread_message_lesson_id_lesson')),
    sa.ForeignKeyConstraint(['parent_id'], ['thread_message.id'], name=op.f('fk_thread_message_parent_id_thread_message')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_thread_message_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thread_message'))
    )
    op.create_index(op.f('ix_thread_message_course_id'), 'thread_message', ['course_id'], unique=False)
    op.create_index(op.f('ix_thread_message_lesson_id'), 'thread_message', ['lesson_id'], unique=False)
    op.create_table('answer',
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('option_ids', postgresql.ARRAY(sa.BigInteger()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempt.id'], name=op.f('fk_answer_attempt_id_quiz_attempt'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_answer_question_id_question')),
    sa.PrimaryKeyConstraint('attempt_id', 'question_id', name=op.f('pk_answer'))
    )
    op.create_table('option',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_option_question_id_question'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option'))
    )
    op.create_index(op.f('ix_option_question_id'), 'option', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_question_id'), table_name='option')
    op.drop_table('option')
    op.drop_table('answer')
    op.drop_index(op.f('ix_thread_message_lesson_id'), table_name='thread_message')
    op.drop_index(op.f('ix_thread_message_course_id'), table_name='thread_message')
    op.drop_table('thread_message')
    op.drop_index(op.f('ix_submission_user_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_task_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_index('uq_quiz_attempt_counted', table_name='quiz_attempt', postgresql_where=sa.text('is_counted'))
    op.drop_index(op.f('ix_quiz_attempt_user_id'), table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_quiz_id'), table_name='quiz_attempt')
    op.drop_table('quiz_attempt')
    op.drop_index(op.f('ix_question_quiz_id'), table_name='question')
    op.drop_table('question')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_lesson_file_lesson_id'), table_name='lesson_file')
    op.drop_table('lesson_file')
    op.drop_index(op.f('ix_task_module_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_quiz_module_id'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_lesson_module_id'), table_name='lesson')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_course_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_module_course_id'), table_name='module')
    op.drop_table('module')
    op.drop_index(op.f('ix_lead_user_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_course_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_enrollment_user_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_course_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_certificate_user_id'), table_name='certificate')
    op.drop_index(op.f('ix_certificate_course_id'), table_name='certificate')
    op.drop_table('certificate')
    op.drop_table('user')
    op.drop_table('setting')
    op.drop_index(op.f('ix_course_group_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_auth_code_phone'), table_name='auth_code')
    op.drop_table('auth_code')
    # ### end Alembic commands ###
