# Миграции вниз не откатываем — чиним новой (backend/CLAUDE.md).
"""course strict_order

Revision ID: b1aee2d4a474
Revises: 00daf3248f9b
Create Date: 2026-08-18 16:01:56.194304

"""
import sqlalchemy as sa
from alembic import op

revision = 'b1aee2d4a474'
down_revision = '00daf3248f9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('strict_order', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'strict_order')
    # ### end Alembic commands ###
