# Миграции вниз не откатываем — чиним новой (backend/CLAUDE.md).
"""session6 certificate conditions and preview

Условия сертификата переезжают в настройки курса четырьмя флагами: редактор
для них появится в сессии 7, а считать выдачу нужно уже сейчас. Проходной балл
сюда не едет — он остаётся у теста, иначе экран результата и чек-лист покажут
разные числа.

Единственность сертификата держит частичный уникальный индекс, а не проверка
в сценарии: двойной клик по «Получить сертификат» не должен выдавать два
документа, а отозванный не должен мешать выдать новый.

preview_course_id — «предпросмотр как учитель» флагом сессии (раздел 12):
гарантия «ничего не записывается» серверная, кукой её не дать.

Revision ID: e171728b2ae2
Revises: e3c40b7d9a12
Create Date: 2026-08-19 01:25:36.214118

"""
import sqlalchemy as sa
from alembic import op

revision = 'e171728b2ae2'
down_revision = 'e3c40b7d9a12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('lang', sa.Text(), server_default='ru', nullable=False))
    op.create_index('uq_certificate_active', 'certificate', ['user_id', 'course_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_check_constraint(op.f('ck_certificate_lang'), 'certificate', "lang IN ('ru', 'kz')")
    op.add_column('course', sa.Column('cert_require_lessons', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('course', sa.Column('cert_require_tasks', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('course', sa.Column('cert_require_module_quizzes', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('course', sa.Column('cert_require_final_quiz', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ix_notification_user_created', 'notification', ['user_id', 'created_at'], unique=False)
    op.add_column('session', sa.Column('preview_course_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_session_preview_course_id_course'), 'session', 'course', ['preview_course_id'], ['id'])
    op.create_index('ix_thread_message_parent', 'thread_message', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thread_message_parent', table_name='thread_message')
    op.drop_constraint(op.f('fk_session_preview_course_id_course'), 'session', type_='foreignkey')
    op.drop_column('session', 'preview_course_id')
    op.drop_index('ix_notification_user_created', table_name='notification')
    op.drop_column('course', 'cert_require_final_quiz')
    op.drop_column('course', 'cert_require_module_quizzes')
    op.drop_column('course', 'cert_require_tasks')
    op.drop_column('course', 'cert_require_lessons')
    op.drop_constraint(op.f('ck_certificate_lang'), 'certificate', type_='check')
    op.drop_index('uq_certificate_active', table_name='certificate', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_column('certificate', 'lang')
    # ### end Alembic commands ###
